### ISSUE TITLE
Linux Compatibility

### ISSUE THREAD

**Issue by jwwood3** [TheMathGeek314/BingoGoalPack1#1]
Hello,
I'm running the mod through lumafly on linux and it isn't loading properly. I get this error in the ModLog.txt file.

> [ERROR]:[API] - System.IO.FileNotFoundException: 
[ERROR]:[API] - File name: '/home/jwwood/.local/share/Steam/steamapps/common/Hollow Knight/.\\\Managed\Mods\BingoSync\BingoSync.dll'

It seems that the mod is looking for the BingoSync mod in the wrong folder, it should be '.../common/Hollow Knight/**hollow_knight_data**/Managed/Mods/BingoSync/BingoSync.dll'
My game install path is set correctly to the Managed folder, so I'm not sure why it would be looking in the wrong place. Any help would be appreciated.

**Comment by TheMathGeek314** [comment]
This is actually an issue with the [BingoSyncExtension](https://github.com/TheRealAlph4/BingoSyncExtension) mod and not BingoGoalPack1. I'll talk to Alpha about resolving the issue.
